import { HospitalAdmission } from "@/lib/hospital-admissions";

export const hospitalAdmissionsGoogleSheet: HospitalAdmission[] = [
  { num: "224", lastName: "ORANA EDUAR", ci: "", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "226", lastName: "SEDENO MARYURI", ci: "14194021", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "243", lastName: "SUCRE FRANCIS MEDINA", ci: "", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "18 anos" },
  { num: "245", lastName: "RONDON FRAN", ci: "19659867", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "246", lastName: "BECERRA LEONARDO", ci: "34800366", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "261", lastName: "VALERO MARIA FELICIA", ci: "13374764", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "262", lastName: "GUILLEN MARIA", ci: "6059288", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "278", lastName: "TIRADO YUNIOR", ci: "26372024", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "279", lastName: "MOSQUERA EMILI", ci: "28285779", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "280", lastName: "DIAS VICTOR", ci: "11537536", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "281", lastName: "ARAQUE MARIA", ci: "28100561", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "283", lastName: "RAMIREZ BARBARA", ci: "18461886", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "284", lastName: "BRITO DAVID", ci: "30678485", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "285", lastName: "DAVILA MARLENE", ci: "19102824", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "286", lastName: "GARCIA MARIO", ci: "5613119", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "287", lastName: "RODRIGUEZ FREDY", ci: "14424783", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "288", lastName: "FIGUEIRA FERNANDA", ci: "81659048", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "289", lastName: "PALMA YOSE", ci: "64488239", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "290", lastName: "ANGARITA CARMEN", ci: "12660680", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "291", lastName: "COLINA YOANDRI", ci: "25872328", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "292", lastName: "YAPTISTA YERMIN", ci: "13948173", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "293", lastName: "DIAS SANDRA", ci: "11638321", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "294", lastName: "DE SANTIAGO JUANA", ci: "11688834", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "296", lastName: "OLIVERO ANA", ci: "4281217", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "297", lastName: "MARTINEZ MARLIN", ci: "10576899", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "298", lastName: "GARCIA JUAN", ci: "17755829", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "334", lastName: "NAVAS YODALIS", ci: "30072743", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
  { num: "336", lastName: "MARTINEZ GABRIEL", ci: "", age: "", sex: "", origin: "", hospital: "Hospital Perez Carreño", updatedAt: "Google Sheet 25/06/2026", service: "Registro hospitalario" },
];
