export type HospitalAdmission = {
  num: string;
  lastName: string;
  ci: string;
  age: string;
  sex: string;
  origin: string;
  hospital: string;
  updatedAt: string;
  service: string;
};

export const hospitalAdmissions: HospitalAdmission[] = [
  {
    "num": "1",
    "lastName": "ABDLY ABDELYS",
    "ci": "26254624",
    "age": "28",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "2",
    "lastName": "ABELLO MATILDE",
    "ci": "",
    "age": "36",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "3",
    "lastName": "Abello Wilmari",
    "ci": "",
    "age": "36",
    "sex": "f",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "4",
    "lastName": "ABREU ANA",
    "ci": "22036301",
    "age": "36",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "5",
    "lastName": "Abreu Emma",
    "ci": "",
    "age": "8",
    "sex": "f",
    "origin": "Sabana Grande",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "6",
    "lastName": "ABREU JOSE",
    "ci": "15810058",
    "age": "52",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "7",
    "lastName": "ABREU PAULINA",
    "ci": "",
    "age": "8",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "8",
    "lastName": "ACOSTA ALEXANDER",
    "ci": "",
    "age": "47",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "9",
    "lastName": "Acosta Ali",
    "ci": "",
    "age": "47",
    "sex": "m",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "10",
    "lastName": "Acosta Hasael",
    "ci": "",
    "age": "13",
    "sex": "m",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "11",
    "lastName": "Acosta Isael",
    "ci": "",
    "age": "10",
    "sex": "m",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "12",
    "lastName": "ACOSTA ISRAEL",
    "ci": "",
    "age": "10",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "13",
    "lastName": "Acosta Yaneli",
    "ci": "31760907",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "14",
    "lastName": "ACOSTA YOLERFAN",
    "ci": "28136168",
    "age": "26",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "15",
    "lastName": "Aguilera Ana",
    "ci": "20003134",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "16",
    "lastName": "ALAYON SUHYN",
    "ci": "",
    "age": "25",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "17",
    "lastName": "Albe Manuel",
    "ci": "",
    "age": "77",
    "sex": "m",
    "origin": "NR",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "18",
    "lastName": "ALCANTARA AMALIS",
    "ci": "17443332",
    "age": "39",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "19",
    "lastName": "ALVAREZ WILIAN",
    "ci": "16125101",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "20",
    "lastName": "ANTEQUIA MAYULI",
    "ci": "12882457",
    "age": "50",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "21",
    "lastName": "ARANA EDUAR",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "22",
    "lastName": "ARRIETA DOLIS",
    "ci": "",
    "age": "65",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "23",
    "lastName": "Arrieta Doris",
    "ci": "",
    "age": "65",
    "sex": "f",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "24",
    "lastName": "ARRIETA OYOLA DORIS",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "25",
    "lastName": "ARTEAGA AIDE",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "26",
    "lastName": "ARTEAGA GLADYS",
    "ci": "",
    "age": "72",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "27",
    "lastName": "Azocar Valeria",
    "ci": "28544619",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "28",
    "lastName": "Balbuena Wilmer",
    "ci": "",
    "age": "37",
    "sex": "m",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "29",
    "lastName": "BALBUENO WILMER",
    "ci": "",
    "age": "37",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "30",
    "lastName": "BARAJA ANDRES",
    "ci": "17491087",
    "age": "41",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "31",
    "lastName": "BARRETO RICARDO",
    "ci": "",
    "age": "42",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "32",
    "lastName": "BASTARDO VERONICA",
    "ci": "30170626",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "33",
    "lastName": "BASTIDA ADRIANA",
    "ci": "17856045",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "35",
    "lastName": "BENEDETTI YORLIANIS",
    "ci": "25846221",
    "age": "29",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "36",
    "lastName": "Bernal Marcela",
    "ci": "6049995",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "37",
    "lastName": "Betancourt Maria",
    "ci": "",
    "age": "74",
    "sex": "f",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "38",
    "lastName": "BISBAL CLARA",
    "ci": "",
    "age": "62",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "39",
    "lastName": "BLANCO CARMEN",
    "ci": "",
    "age": "55",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "40",
    "lastName": "Blanco Jose",
    "ci": "",
    "age": "6",
    "sex": "m",
    "origin": "El Hatillo",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "41",
    "lastName": "BLANCO YESSIKA",
    "ci": "",
    "age": "53",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": "PISO 2"
  },
  {
    "num": "42",
    "lastName": "BOMPARD RODNI",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "43",
    "lastName": "BOSPARTE RONNY",
    "ci": "",
    "age": "33",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "44",
    "lastName": "Boweyo Jose",
    "ci": "26327360",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "45",
    "lastName": "BRACAMONTE GENESIS",
    "ci": "31428533",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "46",
    "lastName": "Brizuela Gabriel",
    "ci": "32781459",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "47",
    "lastName": "Bueno Merido",
    "ci": "17158021",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "48",
    "lastName": "CABARCA YENDERLIN",
    "ci": "",
    "age": "13",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "49",
    "lastName": "CABRERA KARINA",
    "ci": "",
    "age": "30",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": "TRAUMA"
  },
  {
    "num": "50",
    "lastName": "CABRERA KARINA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "51",
    "lastName": "CACERES ELOISE",
    "ci": "11061197",
    "age": "55",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "52",
    "lastName": "CACERES NATHALIA",
    "ci": "36192938",
    "age": "13",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "53",
    "lastName": "CACERES PATRICIA",
    "ci": "32790475",
    "age": "18",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "54",
    "lastName": "CALDERA LEWIS",
    "ci": "",
    "age": "10",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "55",
    "lastName": "CARDENAS ALEXANDRA",
    "ci": "28143770",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "56",
    "lastName": "CARDOZO CARLA",
    "ci": "",
    "age": "25",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "57",
    "lastName": "CARRILLO YASMIN",
    "ci": "5424760",
    "age": "67",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "58",
    "lastName": "Carrizo Viviana",
    "ci": "33232603",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "59",
    "lastName": "CASTAÑEDA MARIA",
    "ci": "",
    "age": "73",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "60",
    "lastName": "CASTAÑO CARLOS",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "61",
    "lastName": "CASTAÑO DANNA",
    "ci": "",
    "age": "12",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "62",
    "lastName": "CASTAÑO DANNA",
    "ci": "",
    "age": "12",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "63",
    "lastName": "CASTELLANO JOSE",
    "ci": "21364204",
    "age": "35",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "64",
    "lastName": "CASTILLO AYARI",
    "ci": "26327913",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "65",
    "lastName": "CASTILLO VICTORIA",
    "ci": "",
    "age": "10",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "66",
    "lastName": "CASTILLO VICTORIA",
    "ci": "",
    "age": "10",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "67",
    "lastName": "CASTRO JUAN",
    "ci": "",
    "age": "26",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "69",
    "lastName": "Chacon Elizabeth",
    "ci": "27374286",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "70",
    "lastName": "Chavez Meri",
    "ci": "81462470",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "71",
    "lastName": "CHIRINOS ALEXANDRA",
    "ci": "31995517",
    "age": "21",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "72",
    "lastName": "CISNERO ROJA",
    "ci": "",
    "age": "57",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "73",
    "lastName": "COA DEIVIS",
    "ci": "18780841",
    "age": "36",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "74",
    "lastName": "Colmenares Darwin",
    "ci": "25867267",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "75",
    "lastName": "CORDERO YADIRA",
    "ci": "12763837",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "76",
    "lastName": "CORDOBA EDUANYELIS",
    "ci": "",
    "age": "6",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "77",
    "lastName": "Cordova Arnaldo",
    "ci": "",
    "age": "19",
    "sex": "m",
    "origin": "Guarenas",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "78",
    "lastName": "Coronel Yonel",
    "ci": "",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "79",
    "lastName": "CORTEZ NOELI",
    "ci": "22538576",
    "age": "30",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "80",
    "lastName": "CORTEZ YORIMAR",
    "ci": "6340991",
    "age": "58",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "81",
    "lastName": "CUYAN FRAN",
    "ci": "10235290",
    "age": "60",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "82",
    "lastName": "De Abreu Geraldine",
    "ci": "18709145",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "83",
    "lastName": "De Anzola Manuela",
    "ci": "296723",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "84",
    "lastName": "DEAGRELA JOSE",
    "ci": "13373135",
    "age": "48",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "85",
    "lastName": "Delgado Edimar",
    "ci": "",
    "age": "23",
    "sex": "f",
    "origin": "San Martin",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "86",
    "lastName": "DIAZ ANA",
    "ci": "10576803",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "87",
    "lastName": "Divito Rosa",
    "ci": "",
    "age": "64",
    "sex": "f",
    "origin": "Chacao",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "88",
    "lastName": "Drana Eduar",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "89",
    "lastName": "ESCALONA IVIS",
    "ci": "",
    "age": "55",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "90",
    "lastName": "ESCALONA JOAQUIN",
    "ci": "6482918",
    "age": "65",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "91",
    "lastName": "ESTEVEZ JOHNSON",
    "ci": "29571733",
    "age": "24",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "92",
    "lastName": "Fernandez Ana",
    "ci": "25699054",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "93",
    "lastName": "FERNANDEZ ANGEL",
    "ci": "16310014",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "94",
    "lastName": "Fernandez Efrain",
    "ci": "",
    "age": "31",
    "sex": "m",
    "origin": "Catia",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "95",
    "lastName": "Fernandez Neisy",
    "ci": "",
    "age": "37",
    "sex": "f",
    "origin": "Guarenas",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "96",
    "lastName": "FERNANDEZ RODRIGO",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "97",
    "lastName": "FRONTADO MIEL",
    "ci": "",
    "age": "7",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": "Qx"
  },
  {
    "num": "98",
    "lastName": "Fuentes Alberto",
    "ci": "",
    "age": "52",
    "sex": "m",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "99",
    "lastName": "FUENTES GALVIS ALBERTO",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "100",
    "lastName": "GARAVITO ESPITIA YOHANY",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "101",
    "lastName": "Garcia Albani",
    "ci": "",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "103",
    "lastName": "Garcia Diego",
    "ci": "33423811",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "104",
    "lastName": "GARCIA HEILIMAR",
    "ci": "32543420",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "105",
    "lastName": "Garcia Jolisbe",
    "ci": "",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "106",
    "lastName": "GARCIA JUVER",
    "ci": "27377514",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "107",
    "lastName": "Garcia Keilimar",
    "ci": "32543420",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "108",
    "lastName": "GEORRIN VALELLA",
    "ci": "30114918",
    "age": "22",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "109",
    "lastName": "Gil Cristofer",
    "ci": "32919700",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "110",
    "lastName": "GODOY ERIC",
    "ci": "18749225",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "111",
    "lastName": "Gomez Manuel",
    "ci": "18814839",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "112",
    "lastName": "GONCALVEZ GABRIEL",
    "ci": "82230906",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "113",
    "lastName": "Gonzalez Albimar",
    "ci": "",
    "age": "59",
    "sex": "f",
    "origin": "Altamira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "114",
    "lastName": "GONZALEZ ALEXANDER",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "115",
    "lastName": "GONZALEZ ALEXANDRA",
    "ci": "",
    "age": "42",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "116",
    "lastName": "Gonzalez Daiberly",
    "ci": "30527436",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "117",
    "lastName": "Gonzalez Elizabeth",
    "ci": "17709218",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "118",
    "lastName": "GONZALEZ ISABEL",
    "ci": "29701695",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "119",
    "lastName": "Gonzalez Mileibis",
    "ci": "26468240",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "120",
    "lastName": "GONZALEZ OLGA",
    "ci": "",
    "age": "63",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "121",
    "lastName": "GONZALEZ RAFAEL",
    "ci": "",
    "age": "39",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "122",
    "lastName": "GONZALEZ STEPHANY",
    "ci": "",
    "age": "22",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "123",
    "lastName": "GONZALEZ VALERI",
    "ci": "",
    "age": "10",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "124",
    "lastName": "Gonzalez Valeria",
    "ci": "31383685",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "125",
    "lastName": "GONZALEZ YANESKA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "126",
    "lastName": "GONZALEZ YURMIS",
    "ci": "13828545",
    "age": "47",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "127",
    "lastName": "GOSLING RAYMOND",
    "ci": "29900166",
    "age": "49",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "128",
    "lastName": "GOYO RAFAEL",
    "ci": "",
    "age": "32",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "129",
    "lastName": "GRANADO CRISBEL",
    "ci": "23936261",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "130",
    "lastName": "GUALINA PADRON EFREN",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "131",
    "lastName": "GUAPINI EFREN P2",
    "ci": "",
    "age": "30",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "132",
    "lastName": "Guerra Emira",
    "ci": "26019884",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "133",
    "lastName": "Guerra Evelin",
    "ci": "17710344",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "134",
    "lastName": "GUERRERO DEIVERSON",
    "ci": "",
    "age": "20",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "135",
    "lastName": "Guessu Estefani",
    "ci": "31428812",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "137",
    "lastName": "Gutierrez Jose",
    "ci": "28747519",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "138",
    "lastName": "GUZMAN ANGELICA",
    "ci": "13717596",
    "age": "",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "139",
    "lastName": "HANMA ANTONIO",
    "ci": "5072832",
    "age": "66",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "140",
    "lastName": "Hernandez Cruz",
    "ci": "4636722",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "141",
    "lastName": "HERRERO MERLANO GLADIUSKA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "142",
    "lastName": "HIDALGO ELIANNI",
    "ci": "32976229",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "143",
    "lastName": "IBARRA ANA",
    "ci": "",
    "age": "74",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "144",
    "lastName": "IBARRA WUIKMER/WILMER",
    "ci": "15332705",
    "age": "45",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "145",
    "lastName": "IDALGO ELIANNI",
    "ci": "32976229",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "146",
    "lastName": "IGLESIAS IBSEN",
    "ci": "32359883",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "147",
    "lastName": "Iscala Yenny",
    "ci": "",
    "age": "42",
    "sex": "f",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "148",
    "lastName": "Izquierdo Jean",
    "ci": "",
    "age": "83",
    "sex": "m",
    "origin": "Los Palos Grandes",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "149",
    "lastName": "JAIMEZ RUBEN DARIO",
    "ci": "6433372",
    "age": "74",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "150",
    "lastName": "JIMENEZ AXIEL",
    "ci": "",
    "age": "4",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": "Qx"
  },
  {
    "num": "151",
    "lastName": "LA VERDE VICTOR",
    "ci": "30334452",
    "age": "18",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "152",
    "lastName": "LANDER SEBASTIAN",
    "ci": "",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "153",
    "lastName": "LANDER SEBASTIAN",
    "ci": "",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "154",
    "lastName": "LEMUS DILCIA",
    "ci": "13531664",
    "age": "54",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "155",
    "lastName": "Leon Gonzalo",
    "ci": "22916224",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "156",
    "lastName": "Liscano Pedro",
    "ci": "",
    "age": "40",
    "sex": "m",
    "origin": "Chacaito",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "157",
    "lastName": "Lopez Dukar",
    "ci": "12115323",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "158",
    "lastName": "LOPEZ EDIS",
    "ci": "6045544",
    "age": "70",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "159",
    "lastName": "LOPEZ FRANCISCA",
    "ci": "33230043",
    "age": "16",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "160",
    "lastName": "LOPEZ FRANLEYDI",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "161",
    "lastName": "LOPEZ HADDY",
    "ci": "",
    "age": "12",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "162",
    "lastName": "LOPEZ INGRID",
    "ci": "10528878",
    "age": "58",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "163",
    "lastName": "LOPEZ MAILIN",
    "ci": "15541666",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "164",
    "lastName": "Lopez Nazare",
    "ci": "",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "165",
    "lastName": "LOPEZ THAIS",
    "ci": "13641870",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "166",
    "lastName": "LOPEZ VALERIA",
    "ci": "31341560",
    "age": "20",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "167",
    "lastName": "LOYO VISBAL CLARA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "168",
    "lastName": "LU DINGPI",
    "ci": "8358411",
    "age": "49",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "169",
    "lastName": "MACHADO ANABELA",
    "ci": "",
    "age": "9",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "171",
    "lastName": "Marcano Katiuska",
    "ci": "",
    "age": "56",
    "sex": "f",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "172",
    "lastName": "Marcano Rosa",
    "ci": "4493435",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "173",
    "lastName": "Marcano Yenni",
    "ci": "18384289",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "174",
    "lastName": "Marquez César",
    "ci": "16312925",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "175",
    "lastName": "Marrero Crismaly",
    "ci": "15164293",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "176",
    "lastName": "MARRERO YORGELIS",
    "ci": "31331652",
    "age": "20",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "177",
    "lastName": "MARTINEZ JESUS",
    "ci": "",
    "age": "7",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "178",
    "lastName": "MARTINEZ JOHAN",
    "ci": "",
    "age": "10",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "179",
    "lastName": "MARTINEZ WUILLIAMS",
    "ci": "19367804",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "180",
    "lastName": "MARTINEZ ZORAIDA",
    "ci": "6692167",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "181",
    "lastName": "MAYORA GUSTAVO",
    "ci": "11643841",
    "age": "52",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "182",
    "lastName": "Mayore Elita",
    "ci": "13069223",
    "age": "",
    "sex": "",
    "origin": "El Junquito",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "183",
    "lastName": "Medina Francis",
    "ci": "285659",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "184",
    "lastName": "MEDINA NATHAELIA/NATHACHA?",
    "ci": "29565365",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "185",
    "lastName": "Mendez Yesiree",
    "ci": "",
    "age": "24",
    "sex": "f",
    "origin": "Guarenas",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "186",
    "lastName": "MENDOZA ANA",
    "ci": "5343446",
    "age": "72",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "187",
    "lastName": "MENDOZA MARIO",
    "ci": "6274191",
    "age": "",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "188",
    "lastName": "MENDOZA REINA",
    "ci": "6887465",
    "age": "62",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "189",
    "lastName": "Mijares Celiana",
    "ci": "19734177",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "190",
    "lastName": "MILANO GLADIUSKA",
    "ci": "",
    "age": "25",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "191",
    "lastName": "MILLAN SOILET",
    "ci": "18142695",
    "age": "39",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "192",
    "lastName": "Miranda Victoria",
    "ci": "34054588",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "193",
    "lastName": "MOLINA NAYIBI",
    "ci": "29768360",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "194",
    "lastName": "MONTILLA NANCY",
    "ci": "10813576",
    "age": "57",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "195",
    "lastName": "Montolla Maria",
    "ci": "25025734",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "196",
    "lastName": "MORA KIMBERLY",
    "ci": "24331288",
    "age": "34",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "197",
    "lastName": "Morales Lesvia",
    "ci": "5965096",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "198",
    "lastName": "MORALES MARIA",
    "ci": "32807709",
    "age": "18",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "199",
    "lastName": "Morillo Anabela",
    "ci": "34588981",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "200",
    "lastName": "MOYANO JAIME",
    "ci": "26346743",
    "age": "28",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "201",
    "lastName": "MUÑON MARIANGEL",
    "ci": "",
    "age": "59",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "202",
    "lastName": "MUÑOZ GEMA",
    "ci": "27797121",
    "age": "24",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "203",
    "lastName": "MUÑOZ JOSEFINA",
    "ci": "",
    "age": "72",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "205",
    "lastName": "NOGUERA FABIAN",
    "ci": "30334636",
    "age": "22",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "206",
    "lastName": "NOVIS CANDELARIO",
    "ci": "9416493",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "207",
    "lastName": "OBREGON DIEGO",
    "ci": "",
    "age": "14",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "208",
    "lastName": "OJEDA CARLOS",
    "ci": "12066889",
    "age": "51",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "209",
    "lastName": "OJEDA YONTACO",
    "ci": "13470155",
    "age": "62",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "210",
    "lastName": "OMACIENTO SEBASTIAN",
    "ci": "",
    "age": "16",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "211",
    "lastName": "ORDAZ LUISANA",
    "ci": "",
    "age": "58",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "212",
    "lastName": "OROPEZA CATIA",
    "ci": "11639511",
    "age": "52",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "213",
    "lastName": "OROPEZA LOURDES",
    "ci": "14312852",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "214",
    "lastName": "OROPEZA SOCORRO",
    "ci": "11639518",
    "age": "53",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "215",
    "lastName": "OROZCO YUSBELIS",
    "ci": "24140952",
    "age": "35",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "216",
    "lastName": "ORTIZ ALVARO",
    "ci": "4163469",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "217",
    "lastName": "Ortuño Yonny",
    "ci": "5199652",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "218",
    "lastName": "PACHECO CESAR",
    "ci": "26327366",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "219",
    "lastName": "PADILLA RODOSKI",
    "ci": "",
    "age": "4",
    "sex": "",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "220",
    "lastName": "PADILLA RODOSKI",
    "ci": "",
    "age": "4",
    "sex": "",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "221",
    "lastName": "PADRON JESUS CIRILO",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "222",
    "lastName": "PALACIO JHON",
    "ci": "25304211",
    "age": "31",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "223",
    "lastName": "PALMA MILAGRO",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "224",
    "lastName": "PANTOJA RAINER",
    "ci": "36085467",
    "age": "17",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "225",
    "lastName": "PANTOJA TONI",
    "ci": "13409559",
    "age": "47",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "226",
    "lastName": "PAREDES YUDI",
    "ci": "3883421",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "227",
    "lastName": "PAREDEZ CRUZCENAIDA",
    "ci": "6405488",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "228",
    "lastName": "Parra Estefania",
    "ci": "",
    "age": "15",
    "sex": "f",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "229",
    "lastName": "PARRA GABRIELA",
    "ci": "",
    "age": "15",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "230",
    "lastName": "PARRA MISEL GABRIELA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "231",
    "lastName": "PEDRO JESUS",
    "ci": "",
    "age": "68",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "232",
    "lastName": "Perdomo Valeria",
    "ci": "",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "233",
    "lastName": "PEREIRA VILLAMIZAR MARIA ISABEL",
    "ci": "",
    "age": "8",
    "sex": "F",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "234",
    "lastName": "PEREZ ARIANI",
    "ci": "24175821",
    "age": "20",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "235",
    "lastName": "PEREZ DAVID",
    "ci": "6842773",
    "age": "61",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "236",
    "lastName": "Perez Enrique",
    "ci": "",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "237",
    "lastName": "PEREZ FRANCISCA",
    "ci": "",
    "age": "63",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "239",
    "lastName": "Perez Katiuska",
    "ci": "18817136",
    "age": "",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "240",
    "lastName": "Perez Misarra",
    "ci": "15550954",
    "age": "",
    "sex": "",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "241",
    "lastName": "Peroza Hilary",
    "ci": "29536127",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "242",
    "lastName": "PEROZA SAMUEL",
    "ci": "33020891",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "243",
    "lastName": "PESTANO MARGARET",
    "ci": "19915985",
    "age": "45",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "244",
    "lastName": "PIÑERO SEBASTIAN",
    "ci": "",
    "age": "16",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "245",
    "lastName": "PLANAS JOSE",
    "ci": "12163470",
    "age": "52",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "246",
    "lastName": "PORTILLO OMAR",
    "ci": "",
    "age": "40",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "247",
    "lastName": "QUINTERO BARBARA",
    "ci": "13422890",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "248",
    "lastName": "QUINTERO CRISDEILIS",
    "ci": "32865296",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "249",
    "lastName": "RAMIREZ ESCALANTE MARIANGEL",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "250",
    "lastName": "RAMIREZ JOSE",
    "ci": "",
    "age": "37",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "251",
    "lastName": "Ramirez Oriana",
    "ci": "27006264",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "252",
    "lastName": "RAMIREZ YILMAR",
    "ci": "22316562",
    "age": "32",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "253",
    "lastName": "RAMOS/SILVA MARYELIS",
    "ci": "32111741",
    "age": "",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "254",
    "lastName": "Rengifo Deili",
    "ci": "",
    "age": "46",
    "sex": "f",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "255",
    "lastName": "RENGIFO GUILLERMINA",
    "ci": "",
    "age": "46",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "256",
    "lastName": "Rey Jennal",
    "ci": "",
    "age": "29",
    "sex": "m",
    "origin": "Chacao",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "257",
    "lastName": "REY JENNICEL",
    "ci": "",
    "age": "29",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "258",
    "lastName": "RIBAS FABIANA",
    "ci": "",
    "age": "23",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "259",
    "lastName": "RIVAS FRANKENIL",
    "ci": "",
    "age": "53",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "260",
    "lastName": "RIVAS LOPEZ FRANCIS",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "261",
    "lastName": "Rivero Daniel",
    "ci": "",
    "age": "60",
    "sex": "m",
    "origin": "Macaracuay",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "262",
    "lastName": "Rivero Karleidi",
    "ci": "36091784",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "263",
    "lastName": "RODOSKI PADILLA",
    "ci": "",
    "age": "52",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "264",
    "lastName": "Rodriguez Eduardo",
    "ci": "",
    "age": "65",
    "sex": "m",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "265",
    "lastName": "RODRIGUEZ EDUARDO",
    "ci": "",
    "age": "65",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "266",
    "lastName": "Rodriguez Kiara Antonia",
    "ci": "",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "267",
    "lastName": "RODRIGUEZ MAIKEL",
    "ci": "16208203",
    "age": "42",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "268",
    "lastName": "ROJAS RAFAEL",
    "ci": "",
    "age": "50",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "269",
    "lastName": "ROMERO JOSE",
    "ci": "",
    "age": "60",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "270",
    "lastName": "Rondon Angel",
    "ci": "",
    "age": "12",
    "sex": "m",
    "origin": "Baruta",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "271",
    "lastName": "RONDON DAYANA",
    "ci": "",
    "age": "18",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "273",
    "lastName": "ROSIER LIZ",
    "ci": "26068002",
    "age": "28",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "274",
    "lastName": "RUEDA JOSE",
    "ci": "15430608",
    "age": "45",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "275",
    "lastName": "SALAZAR ARTURO",
    "ci": "",
    "age": "13",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "276",
    "lastName": "SALAZAR ARTURO",
    "ci": "",
    "age": "13",
    "sex": "M",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "277",
    "lastName": "SALAZAR JUAN",
    "ci": "27044236",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "278",
    "lastName": "SANCHEZ JOSE",
    "ci": "32320521",
    "age": "19",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "279",
    "lastName": "Sandoval Adriana",
    "ci": "34518879",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": ""
  },
  {
    "num": "280",
    "lastName": "SANDOVAL DORIS",
    "ci": "4029093",
    "age": "80",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "281",
    "lastName": "SEMERIA IRLLIS",
    "ci": "",
    "age": "49",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "282",
    "lastName": "SEQUERA BLANCO SOFIA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "283",
    "lastName": "SEQUERA SOFIA",
    "ci": "",
    "age": "15",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "284",
    "lastName": "SERRANO GONZALEZ NANCY",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "285",
    "lastName": "SERRANO NANCY",
    "ci": "",
    "age": "67",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "286",
    "lastName": "SILVA IBRAHIM",
    "ci": "20562844",
    "age": "35",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "287",
    "lastName": "SILVA INDIANA",
    "ci": "14929760",
    "age": "",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "288",
    "lastName": "SIVIRA LEONEIDY",
    "ci": "25175345",
    "age": "30",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "289",
    "lastName": "SOLORZANO AMAR ÑO",
    "ci": "31445070",
    "age": "18",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "290",
    "lastName": "SOMOZA RIAND",
    "ci": "15267293",
    "age": "19",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "291",
    "lastName": "SOSA EMILIA",
    "ci": "3409148",
    "age": "78",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "292",
    "lastName": "SOZA ALEJANDRA",
    "ci": "6904629",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "293",
    "lastName": "SPINOLA KELLY",
    "ci": "17482090",
    "age": "38",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "294",
    "lastName": "STABILITO AMILCAR",
    "ci": "23241059",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "295",
    "lastName": "SUAREZ GRANADO RENE",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "296",
    "lastName": "SUAREZ RENE",
    "ci": "",
    "age": "62",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "297",
    "lastName": "Sucre Petra",
    "ci": "2945823",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRAUMASHOCK"
  },
  {
    "num": "298",
    "lastName": "TERAN AUDIA",
    "ci": "11055173",
    "age": "54",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "299",
    "lastName": "Teran Audia",
    "ci": "11055173",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "300",
    "lastName": "TERAN TENIA",
    "ci": "11409997",
    "age": "55",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "301",
    "lastName": "Torrealba Nuvia",
    "ci": "",
    "age": "68",
    "sex": "f",
    "origin": "Chacao",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "302",
    "lastName": "TORREALBA RODRIGUEZ SEBASTIAN",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "CIUDAD CARIBIA",
    "hospital": "JM DE LOS RIOS (HOSP DE NIÑOS)",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "303",
    "lastName": "Torres Isabel",
    "ci": "4718019",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "304",
    "lastName": "TORRES MILAGROS",
    "ci": "",
    "age": "46",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "305",
    "lastName": "TORTOSO OSCAR",
    "ci": "20558047",
    "age": "37",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "307",
    "lastName": "TOVAR YEISON",
    "ci": "",
    "age": "17",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "308",
    "lastName": "TRIGOSO CARLO",
    "ci": "8418724",
    "age": "59",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "309",
    "lastName": "Trujillo Elian",
    "ci": "",
    "age": "19",
    "sex": "m",
    "origin": "La Guaira",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "310",
    "lastName": "URBINA MOISES",
    "ci": "22513789",
    "age": "30",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "311",
    "lastName": "Uribe Veronica",
    "ci": "22026527",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "312",
    "lastName": "VALERO FLEICI",
    "ci": "13374754",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "313",
    "lastName": "Varya Carmen",
    "ci": "22550086",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "314",
    "lastName": "VASCOCETO ANDREINA",
    "ci": "",
    "age": "43",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "315",
    "lastName": "VASCONCELO ANDREINA",
    "ci": "",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "316",
    "lastName": "Vasquez Luis",
    "ci": "",
    "age": "77",
    "sex": "m",
    "origin": "sin familiar",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "317",
    "lastName": "Vega Samuel",
    "ci": "",
    "age": "11",
    "sex": "m",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "318",
    "lastName": "Velazquez Carmen",
    "ci": "16705956",
    "age": "",
    "sex": "F",
    "origin": "La Guaira",
    "hospital": "Hospital Vargas de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "319",
    "lastName": "VIERA ROSALINDA",
    "ci": "12717087",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "320",
    "lastName": "Vilchez Brayan",
    "ci": "",
    "age": "23",
    "sex": "m",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "321",
    "lastName": "VOVIS CANDELARIO",
    "ci": "9416493",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "25/6/26",
    "service": ""
  },
  {
    "num": "322",
    "lastName": "Winchester Kellys",
    "ci": "",
    "age": "28",
    "sex": "f",
    "origin": "Petare",
    "hospital": "Hospital Domingo Luciani (El Llanito)",
    "updatedAt": "25/6/26 1.50am",
    "service": ""
  },
  {
    "num": "323",
    "lastName": "WU HUA JUAN",
    "ci": "8229616",
    "age": "47",
    "sex": "M",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "324",
    "lastName": "WU SUSUP",
    "ci": "34553337",
    "age": "14",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  },
  {
    "num": "325",
    "lastName": "YANES SILVIA",
    "ci": "3557870",
    "age": "77",
    "sex": "",
    "origin": "",
    "hospital": "Hopital Ricardo Baquero Gonzalez",
    "updatedAt": "25/6/26",
    "service": "Cirugía General"
  },
  {
    "num": "326",
    "lastName": "Yegue Eiban",
    "ci": "24058780",
    "age": "",
    "sex": "",
    "origin": "",
    "hospital": "Hospital Perez Carreño",
    "updatedAt": "24/6/26 11.54pm",
    "service": "TRIAJE"
  },
  {
    "num": "327",
    "lastName": "ZAMBRANO DOMINI",
    "ci": "18274233",
    "age": "39",
    "sex": "F",
    "origin": "",
    "hospital": "Hospital Universitario de Caracas",
    "updatedAt": "25/6/26 pm",
    "service": ""
  }
];
