import { HospitalAdmission } from "@/lib/hospital-admissions";

export const hospitalAdmissionsOeste: HospitalAdmission[] = [
  { num: "1", lastName: "BERMUDEZ GENESIS", ci: "20925605", age: "", sex: "", origin: "Caribe", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "2", lastName: "GENIRE ELIANGELIS", ci: "33916827", age: "", sex: "", origin: "Maiquetia", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "3", lastName: "HERNANDEZ EDEVAN", ci: "14935718", age: "", sex: "", origin: "Playa Verde", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Sin familia" },
  { num: "4", lastName: "ARRIETA JOSE", ci: "15720959", age: "", sex: "", origin: "Catia la Mar", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "5", lastName: "ZAPATA CARMEN", ci: "6856684", age: "", sex: "", origin: "Mare", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "6", lastName: "PEREZ AMBAR", ci: "25964449", age: "", sex: "", origin: "Casarabia", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "7", lastName: "TORRES JENNY", ci: "15834314", age: "", sex: "", origin: "Caribe", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "8", lastName: "GIL MICHELLE", ci: "30041537", age: "", sex: "", origin: "Playa Grande", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "9", lastName: "TOVAR SAMUEL", ci: "30010914", age: "", sex: "", origin: "Caribe", hospital: "Hospital General del Oeste", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "10", lastName: "BERMUDEZ GENESIS", ci: "20925605", age: "33", sex: "", origin: "La Guaira", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Fractura de miembros inferiores" },
  { num: "11", lastName: "ARANGUREN YONAIKER", ci: "", age: "21", sex: "", origin: "Los Corales", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Politraumatismos" },
  { num: "12", lastName: "MATA YOALBERT", ci: "", age: "7", sex: "", origin: "Playa Grande", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Traumatismo facial" },
  { num: "13", lastName: "URUCHUTO ALEXANDER", ci: "", age: "37", sex: "", origin: "", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Traumatismo de rodilla y hombro" },
  { num: "14", lastName: "RONDON DAYANARA", ci: "", age: "19", sex: "", origin: "", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Traumatismo craneal" },
  { num: "15", lastName: "HERNANDEZ ESTEBAN", ci: "14935718", age: "47", sex: "", origin: "Playa Verde", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Fractura de tibia y perone - SIN FAMILIARES / UNICO SOBREVIVIENTE" },
  { num: "16", lastName: "ZAPATA CARMEN", ci: "6856684", age: "66", sex: "", origin: "Mare II", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Fractura de femur" },
  { num: "17", lastName: "ARRIETA JOSE", ci: "15720959", age: "45", sex: "", origin: "Catia La Mar", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Fractura de femur" },
  { num: "18", lastName: "DAREN ELIANYELIS", ci: "", age: "15", sex: "", origin: "Maiquetia", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Contusion craneal" },
  { num: "19", lastName: "TORRES PENA YENNY DAMARIS", ci: "15834314", age: "", sex: "", origin: "Ciudad Caribea", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Politraumatismos - Tx toraco abdominal no complicado" },
  { num: "20", lastName: "ALVAREZ MAIKELI", ci: "300454425", age: "", sex: "", origin: "La Guaira", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Politraumatismo" },
  { num: "21", lastName: "TOVAR SAMUEL", ci: "35010914", age: "13", sex: "", origin: "Ciudad Caribea", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Politraumatismo" },
  { num: "22", lastName: "PEEREZ AMBAR", ci: "25964449", age: "28", sex: "", origin: "Guarenas", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Traumatismo tobillo" },
  { num: "23", lastName: "INFANTE JAIMES", ci: "6261045", age: "59", sex: "", origin: "Catia La Mar", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Politraumatismos" },
  { num: "24", lastName: "GIL MICHEL", ci: "30091537", age: "22", sex: "", origin: "Playa Grande", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Registro hospitalario" },
  { num: "25", lastName: "GUEIRA JUAN", ci: "17755824", age: "40", sex: "", origin: "Guarenas", hospital: "Hospital Dr. Jose Gregorio Hernandez", updatedAt: "Carga manual 25/06/2026", service: "Politraumatismos" },
];
