import { HospitalAdmission } from "@/lib/hospital-admissions";

export const hospitalAdmissionsHucReport: HospitalAdmission[] = [
  {
    num: "1",
    lastName: "MARIA MOSQUERA",
    ci: "",
    age: "18",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "FALLECIO AL INGRESO",
  },
  {
    num: "2",
    lastName: "LIA SILVA",
    ci: "",
    age: "4",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "FALLECIDO",
  },
  {
    num: "3",
    lastName: "MARISA MORALES",
    ci: "32809709",
    age: "18",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "FALLECIDO",
  },
  {
    num: "3",
    lastName: "NANCY MONTILLA",
    ci: "10513576",
    age: "57",
    sex: "",
    origin: "EL CEMENTERIO",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "5",
    lastName: "DONMANI ZAMBRANO",
    ci: "18714233",
    age: "39",
    sex: "",
    origin: "CATIA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "9",
    lastName: "ANTONIO AHANMA",
    ci: "2072832",
    age: "66",
    sex: "",
    origin: "AV. ROOSEVELT",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "10",
    lastName: "DEIVYS COA",
    ci: "18760841",
    age: "36",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "11",
    lastName: "JOSE RUEDA",
    ci: "15460603",
    age: "45",
    sex: "",
    origin: "AV. LIBERTADOR",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "16",
    lastName: "JAIME MOYANO",
    ci: "26346745",
    age: "28",
    sex: "",
    origin: "MARICHE",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "20",
    lastName: "LUISANA TOVAR",
    ci: "17443950",
    age: "17",
    sex: "",
    origin: "EL VALLE",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "21",
    lastName: "YASMIN CARRILLO",
    ci: "5424960",
    age: "67",
    sex: "",
    origin: "LOS ROSALES",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "22",
    lastName: "FABIAN NOGUERA",
    ci: "30334666",
    age: "22",
    sex: "",
    origin: "PINTO SALINAS",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "25",
    lastName: "JOSE LUIS ABREU",
    ci: "15800038",
    age: "47",
    sex: "",
    origin: "HOYO DE LA PUERTA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "26",
    lastName: "LUIGI PONCE",
    ci: "18042519",
    age: "39",
    sex: "",
    origin: "GRAMOVEN",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "28",
    lastName: "ANDREINA CUBA",
    ci: "25000118",
    age: "30",
    sex: "",
    origin: "EL VALLE",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "29",
    lastName: "JOSE SANCHEZ",
    ci: "32320251",
    age: "19",
    sex: "",
    origin: "CARRIZAL",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "30",
    lastName: "MARGOT SOLORZANO",
    ci: "3405970",
    age: "68",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "31",
    lastName: "RICHARTSON GUZMAN",
    ci: "26938811",
    age: "27",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "32",
    lastName: "LU DINGYI",
    ci: "83584110",
    age: "44",
    sex: "",
    origin: "LA GUIARA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "33",
    lastName: "NATALIA MORA",
    ci: "28312526",
    age: "25",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "34",
    lastName: "HUA JIAH WU",
    ci: "82296160",
    age: "47",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "35",
    lastName: "LIZ CLOSIER",
    ci: "26063002",
    age: "28",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "36",
    lastName: "SUSANA WU",
    ci: "36533334",
    age: "14",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "38",
    lastName: "PATRICIA CACERES",
    ci: "332730475",
    age: "18",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "39",
    lastName: "WILMER IBARRA",
    ci: "15335705",
    age: "45",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "40",
    lastName: "JOSE CACERES",
    ci: "11061147",
    age: "55",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "41",
    lastName: "EDIS LOPEZ",
    ci: "6045349",
    age: "70",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "42",
    lastName: "SOBEIDA OROPEZA",
    ci: "11635518",
    age: "53",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "44",
    lastName: "VICTOR LA VENDE",
    ci: "3344528",
    age: "18",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "45",
    lastName: "RAYMOND GOSLING",
    ci: "2900166",
    age: "79",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "46",
    lastName: "ABRIL SILVA",
    ci: "16106829",
    age: "6",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "47",
    lastName: "ABRAHAN SILVA",
    ci: "20568419",
    age: "35",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "48",
    lastName: "INDIRA DE SILVA",
    ci: "14556746",
    age: "46",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "49",
    lastName: "NURIA GOMEZ",
    ci: "11926425",
    age: "80",
    sex: "",
    origin: "NO ESPECIFICA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "50",
    lastName: "MAYELY RAMOS",
    ci: "32111714",
    age: "18",
    sex: "",
    origin: "NO ESPECIFICA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "51",
    lastName: "EDITH AVILA",
    ci: "31073850",
    age: "20",
    sex: "",
    origin: "LAS ADJUNTAS",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "TRAUMATISMO LEVE",
  },
  {
    num: "52",
    lastName: "EDGAR GONZALEZ",
    ci: "16310437",
    age: "40",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "ALTA MEDICA",
  },
  {
    num: "53",
    lastName: "YASMIN DIAZ",
    ci: "13999719",
    age: "47",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "54",
    lastName: "DIEGO CAMARGO",
    ci: "11926425",
    age: "29",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "55",
    lastName: "MIRIAM GARCIA",
    ci: "32111714",
    age: "58",
    sex: "",
    origin: "FUERTE TIUNA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "56",
    lastName: "GLORIA RUANO",
    ci: "3806228",
    age: "76",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "57",
    lastName: "MAITE TEJERA",
    ci: "14073961",
    age: "46",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "58",
    lastName: "MATIAS UMBRIA",
    ci: "22034962",
    age: "11",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "59",
    lastName: "MAIRA FLORES",
    ci: "14955107",
    age: "44",
    sex: "",
    origin: "LA GUIARA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "60",
    lastName: "GERAL CASTRO",
    ci: "31656363",
    age: "11",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "61",
    lastName: "ROSIBEL SANCHEZ",
    ci: "15844713",
    age: "43",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "62",
    lastName: "MARIA HENRIQUE",
    ci: "14213277",
    age: "46",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "63",
    lastName: "MIGUEL RODRIGUEZ",
    ci: "14299716",
    age: "88",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "64",
    lastName: "MARIA HENRIQUE",
    ci: "8471007",
    age: "64",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "65",
    lastName: "SABRINA PAEZ",
    ci: "",
    age: "18",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "66",
    lastName: "DANIEL DIAZ",
    ci: "10001561",
    age: "57",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "67",
    lastName: "GAUDY GRANADO",
    ci: "15586408",
    age: "46",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
  {
    num: "68",
    lastName: "ANGEL GARCIA",
    ci: "14299523",
    age: "46",
    sex: "",
    origin: "LA GUAIRA",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Reporte HUC 24/06/2026",
    service: "POLITRAUMATISMO",
  },
];
