import { HospitalAdmission } from "@/lib/hospital-admissions";

export const hospitalAdmissionsSupplemental: HospitalAdmission[] = [
  {
    num: "DL-01",
    lastName: "RUIZ DENNIS",
    ci: "",
    age: "41",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-02",
    lastName: "GONZALEZ FRANCISCA",
    ci: "",
    age: "83",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-03",
    lastName: "FIGUEROA ALAN",
    ci: "",
    age: "14",
    sex: "",
    origin: "Caribe",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-04",
    lastName: "MAYORCA DAVID",
    ci: "",
    age: "26",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-05",
    lastName: "CASTALLERO MARIA",
    ci: "",
    age: "65",
    sex: "",
    origin: "Quarena",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-06",
    lastName: "AL-NABI JANETH",
    ci: "",
    age: "56",
    sex: "",
    origin: "Caribe",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-07",
    lastName: "GONZALEZ ALEXANDRA",
    ci: "",
    age: "47",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am",
  },
  {
    num: "DL-08",
    lastName: "GOMEAL LUCY",
    ci: "",
    age: "61",
    sex: "",
    origin: "Caribe",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Politrauma (MI) - 7:20 am - TRM",
  },
  {
    num: "DL-09",
    lastName: "GILDERT ANA",
    ci: "",
    age: "4",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Pediatria - 7:40 am",
  },
  {
    num: "DL-10",
    lastName: "CAVARCA YIRBELY",
    ci: "",
    age: "13",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Pediatria - 7:40 am",
  },
  {
    num: "DL-11",
    lastName: "GARCIA BRADIAN",
    ci: "",
    age: "8",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Pediatria - 7:40 am",
  },
  {
    num: "DL-12",
    lastName: "LENDI SEBASTIAN",
    ci: "",
    age: "7",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Pediatria - 7:40 am",
  },
  {
    num: "DL-13",
    lastName: "FONTADO MIEL",
    ci: "",
    age: "7",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Pediatria - 7:40 am",
  },
  {
    num: "DL-14",
    lastName: "CASTILLO VICTORIA",
    ci: "",
    age: "10",
    sex: "",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Pediatria - 7:40 am",
  },
  {
    num: "DL-15",
    lastName: "REBOREDO LUIS",
    ci: "",
    age: "57",
    sex: "M",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Poli I - 7:30 am",
  },
  {
    num: "DL-16",
    lastName: "FARINEZ ARELIS",
    ci: "",
    age: "53",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Poli I - 7:30 am",
  },
  {
    num: "DL-17",
    lastName: "BAUTE MIRELIS",
    ci: "",
    age: "65",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Poli I - 7:30 am - Alta medica",
  },
  {
    num: "DL-18",
    lastName: "BLANCO YESICA",
    ci: "",
    age: "53",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Poli I - 7:30 am",
  },
  {
    num: "DL-19",
    lastName: "RAMIREZ NAIROBY",
    ci: "",
    age: "",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Poli I - 7:30 am - S/P",
  },
  {
    num: "DL-20",
    lastName: "CABRERA KARINA",
    ci: "",
    age: "30",
    sex: "F",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-21",
    lastName: "MIRANDA JOSEPH",
    ci: "",
    age: "24",
    sex: "M",
    origin: "Katia",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-22",
    lastName: "CARRASQUEL SANTIAGO",
    ci: "",
    age: "14",
    sex: "M",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-23",
    lastName: "ECHARTE DORIS",
    ci: "",
    age: "23",
    sex: "F",
    origin: "23 Enero",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-24",
    lastName: "ASCANIO LUIS",
    ci: "",
    age: "15",
    sex: "M",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-25",
    lastName: "GARCIA JOSE",
    ci: "",
    age: "59",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-26",
    lastName: "FERNANDEZ YASQUEIDY",
    ci: "",
    age: "35",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-27",
    lastName: "RODRIGUEZ MARIA",
    ci: "",
    age: "82",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-28",
    lastName: "VEGUIDA MAURO",
    ci: "",
    age: "55",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-29",
    lastName: "BOSPORTE RONY",
    ci: "",
    age: "33",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-30",
    lastName: "CLASTA CLARA INES",
    ci: "",
    age: "62",
    sex: "",
    origin: "Petare",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-31",
    lastName: "ARTEAGA AIDEE",
    ci: "",
    age: "72",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-32",
    lastName: "SANCHEZ CATALINA",
    ci: "",
    age: "64",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-33",
    lastName: "AL HALABI MAHNUOR",
    ci: "",
    age: "56",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-34",
    lastName: "CARRASQUEL SEBASTIAN",
    ci: "",
    age: "12",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-35",
    lastName: "BOADA EVELY",
    ci: "",
    age: "54",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-36",
    lastName: "RIVAS FABIANA",
    ci: "",
    age: "23",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-37",
    lastName: "MORENO GISMELI",
    ci: "",
    age: "31",
    sex: "",
    origin: "Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "EMG Trauma - 7:46 am",
  },
  {
    num: "DL-38",
    lastName: "FERNANDEZ EMELY",
    ci: "",
    age: "31",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Medicina Interna - 9:00 am - Poli",
  },
  {
    num: "DL-39",
    lastName: "RODRIGUEZ JESUS",
    ci: "",
    age: "28",
    sex: "M",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Medicina Interna - 9:00 am",
  },
  {
    num: "DL-40",
    lastName: "CARDOZA KARLA",
    ci: "",
    age: "25",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Medicina Interna - 9:00 am",
  },
  {
    num: "DL-41",
    lastName: "ODEBE MANUEL",
    ci: "",
    age: "38",
    sex: "M",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Medicina Interna - 9:00 am",
  },
  {
    num: "DL-42",
    lastName: "IZQUIERDO ENRIQUE",
    ci: "",
    age: "63",
    sex: "M",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Medicina Interna - 9:00 am",
  },
  {
    num: "DL-43",
    lastName: "GARCIA ODALYS",
    ci: "",
    age: "43",
    sex: "F",
    origin: "",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Medicina Interna - 9:00 am",
  },
  {
    num: "DL-44",
    lastName: "VEGA ISABEL",
    ci: "",
    age: "50",
    sex: "F",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Poli Emerg Nueva - 26/06/2026",
  },
  {
    num: "DL-45",
    lastName: "LISCANO PEDRO",
    ci: "",
    age: "46",
    sex: "M",
    origin: "Chacaito",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Terapia - 26/06/2026",
  },
  {
    num: "DL-46",
    lastName: "CELIS TANIA",
    ci: "",
    age: "62",
    sex: "F",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Terapia - 26/06/2026",
  },
  {
    num: "DL-47",
    lastName: "TRUJILLO HERIAM",
    ci: "",
    age: "19",
    sex: "M",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Terapia - 26/06/2026",
  },
  {
    num: "DL-48",
    lastName: "TORRES MILAGROS",
    ci: "",
    age: "46",
    sex: "F",
    origin: "La Guaira",
    hospital: "Hospital Dr. Domingo Luciani",
    updatedAt: "Reporte Luciani 26/06/2026",
    service: "Terapia - 26/06/2026",
  },
  {
    num: "6",
    lastName: "BENEDETI YORLIANIS",
    ci: "",
    age: "29",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "7",
    lastName: "TRIGOSO CARLOS",
    ci: "",
    age: "59",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "9",
    lastName: "TOVAR LUISONA",
    ci: "",
    age: "17",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "10",
    lastName: "CARILLO YASMIN",
    ci: "",
    age: "67",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "27",
    lastName: "DANTOJA TONI",
    ci: "",
    age: "47",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "39",
    lastName: "SOLORZANO OMARÑO",
    ci: "",
    age: "18",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "44",
    lastName: "CÁCERES NATHALIA",
    ci: "",
    age: "13",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "45",
    lastName: "CÁCERES PATRICIA",
    ci: "",
    age: "18",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "46",
    lastName: "CÁCERES ELIOSE",
    ci: "",
    age: "55",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "49",
    lastName: "LÓPEZ EDIS",
    ci: "",
    age: "70",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "52",
    lastName: "GOSLING HAIRMON",
    ci: "",
    age: "49",
    sex: "",
    origin: "",
    hospital: "Hospital Universitario de Caracas",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "60",
    lastName: "RAMÍREZ ELEYSA",
    ci: "",
    age: "64",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "61",
    lastName: "RODRÍGUEZ MARBELIS",
    ci: "",
    age: "52",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "62",
    lastName: "RODRÍGUEZ YALITZA",
    ci: "",
    age: "57",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "63",
    lastName: "ZHANGYOU CHEN",
    ci: "",
    age: "57",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "64",
    lastName: "CHEN BOYE",
    ci: "",
    age: "21",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "65",
    lastName: "FRANCO ANTONIO",
    ci: "",
    age: "63",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "66",
    lastName: "BARRETO IRAMA",
    ci: "",
    age: "74",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "67",
    lastName: "MOISES (menor)",
    ci: "",
    age: "5",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "68",
    lastName: "PÉREZ CECALIO",
    ci: "",
    age: "72",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "69",
    lastName: "MOY MARIA",
    ci: "",
    age: "47",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "70",
    lastName: "PÉREZ CARMEN",
    ci: "",
    age: "64",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "71",
    lastName: "OMAÑA RAIZA",
    ci: "",
    age: "45",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "72",
    lastName: "BELANDRIA JOFFRE",
    ci: "",
    age: "63",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "73",
    lastName: "BEGOCHEA REINALDO",
    ci: "",
    age: "43",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "74",
    lastName: "MACHADO CARMEN",
    ci: "",
    age: "77",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "75",
    lastName: "HERNÁNDEZ JACKELINE",
    ci: "",
    age: "62",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "76",
    lastName: "TINGY JOSÉ",
    ci: "",
    age: "44",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "77",
    lastName: "MUÑOZ CAMILA",
    ci: "",
    age: "15",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "78",
    lastName: "LLORET LAURA",
    ci: "",
    age: "85",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "79",
    lastName: "LLORET LILIANA",
    ci: "",
    age: "59",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "80",
    lastName: "CEDEÑO CARLOS",
    ci: "",
    age: "76",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "81",
    lastName: "VARELA ANGEL",
    ci: "",
    age: "47",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "82",
    lastName: "ARTEAGA BETI",
    ci: "",
    age: "51",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "83",
    lastName: "GUERRA PETRA",
    ci: "",
    age: "72",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "84",
    lastName: "GARCÍA ANTONIO",
    ci: "",
    age: "36",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "85",
    lastName: "ALVARADO NAIROBIS",
    ci: "",
    age: "32",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "86",
    lastName: "QUERALES ALEIDA",
    ci: "",
    age: "64",
    sex: "",
    origin: "",
    hospital: "Cruz Roja",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "87",
    lastName: "CASTILLO JORGE",
    ci: "",
    age: "26",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "88",
    lastName: "SÁNCHEZ MARIA",
    ci: "",
    age: "77",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "89",
    lastName: "RODRÍGUEZ CINDY",
    ci: "",
    age: "30",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "90",
    lastName: "PABÓN MARIANGEL",
    ci: "",
    age: "21",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "91",
    lastName: "COLMENARAS YADHER",
    ci: "",
    age: "3",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "92",
    lastName: "MARY DURÓN",
    ci: "",
    age: "36",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "93",
    lastName: "CONTRERAS VALERIA",
    ci: "",
    age: "18",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "94",
    lastName: "MORENO YADER",
    ci: "",
    age: "24",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "95",
    lastName: "ESPINOSA FERMÍNE",
    ci: "",
    age: "70",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "96",
    lastName: "CAPELLA HAROLD",
    ci: "",
    age: "33",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "97",
    lastName: "VALENCIA ELIX",
    ci: "",
    age: "43",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "98",
    lastName: "RODRÍGUEZ SANELLY",
    ci: "",
    age: "12",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "99",
    lastName: "MAYOR HENDERSON",
    ci: "",
    age: "15",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "100",
    lastName: "LÓPEZ MARIOLY",
    ci: "",
    age: "44",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "101",
    lastName: "HADDAN YALEISY",
    ci: "",
    age: "41",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "102",
    lastName: "ALBINO WALTER",
    ci: "",
    age: "45",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "103",
    lastName: "GONZÁLEZ ANDERSON",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "104",
    lastName: "LAMA DANIELA",
    ci: "",
    age: "3",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "105",
    lastName: "HERLANE LÓPEZ",
    ci: "",
    age: "68",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "106",
    lastName: "LÓPEZ NEIBOY",
    ci: "",
    age: "22",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "107",
    lastName: "CIPRIOTA SEVILLE",
    ci: "",
    age: "29",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "108",
    lastName: "QUETOY YSABEL",
    ci: "",
    age: "36",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "109",
    lastName: "PASTONO GYAMILY",
    ci: "",
    age: "32",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "110",
    lastName: "RODRÍGUEZ PINDIOLE",
    ci: "",
    age: "51",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "111",
    lastName: "FRANKLIN ALFONSO",
    ci: "",
    age: "65",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "112",
    lastName: "SALAZAR CAROLINE",
    ci: "",
    age: "6",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "113",
    lastName: "MARTÍNEZ YAMILITH",
    ci: "",
    age: "30",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "114",
    lastName: "RIVAS MARY",
    ci: "",
    age: "30",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "115",
    lastName: "PENA YOHSEN",
    ci: "",
    age: "51",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "116",
    lastName: "ZEALARIO ALEXIS",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "117",
    lastName: "GONZÁLEZ ANA",
    ci: "",
    age: "46",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "118",
    lastName: "ENDER RANGEL",
    ci: "",
    age: "150",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "119",
    lastName: "YACHER NANCY DURÁN",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "120",
    lastName: "VALERIA CONTRERAS",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "121",
    lastName: "YARLYS CONTRERAS",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "122",
    lastName: "FERMÍNE ESPINOSA",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "123",
    lastName: "HAROLD CAPELLA",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "124",
    lastName: "ALEX PALENCIA",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "125",
    lastName: "DANELY RODRÍGUEZ",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "126",
    lastName: "HELINSSON AQUINO",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "127",
    lastName: "YALEISY HADDAN",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "128",
    lastName: "GORDOFÓN GONZALEZ",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "129",
    lastName: "CERVELAN FERMÍNE",
    ci: "",
    age: "",
    sex: "",
    origin: "",
    hospital: "Periférico de Catia",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "132",
    lastName: "GARCIA YENNY",
    ci: "",
    age: "34",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "139",
    lastName: "BALBUENO WILMED",
    ci: "",
    age: "37",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "142",
    lastName: "RONDÓN ANGEL",
    ci: "",
    age: "12",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "145",
    lastName: "MIJARES ISOLIBETH",
    ci: "",
    age: "45",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "146",
    lastName: "URBINA SILIBETO",
    ci: "",
    age: "80",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "147",
    lastName: "BORGES LILIANE",
    ci: "",
    age: "21",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "149",
    lastName: "BISVAL CLARA",
    ci: "",
    age: "62",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "155",
    lastName: "RAMÍREZ MARIANGEL",
    ci: "",
    age: "33",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "156",
    lastName: "BLANCOS YESSICA",
    ci: "",
    age: "53",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "157",
    lastName: "RIVAS FABINA",
    ci: "",
    age: "23",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "158",
    lastName: "MILANO GLADIVSKA",
    ci: "",
    age: "29",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "162",
    lastName: "PIRETO SEBASTIÁN",
    ci: "",
    age: "16",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "165",
    lastName: "CABEZA KARINA",
    ci: "",
    age: "30",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "167",
    lastName: "CHACÓN CARLOS",
    ci: "",
    age: "43",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "168",
    lastName: "LOPEZ HADDY F",
    ci: "",
    age: "42",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "170",
    lastName: "CASTAÑO DANA",
    ci: "",
    age: "17",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "177",
    lastName: "MARABITO JOSEANI",
    ci: "",
    age: "32",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "182",
    lastName: "CÓRDOVA ARNALDO",
    ci: "",
    age: "19",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "194",
    lastName: "GUAVINI EFREN P.2",
    ci: "",
    age: "30",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "195",
    lastName: "CISNERO ROSA",
    ci: "",
    age: "57",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "201",
    lastName: "IZQUIERDO IRAIMA",
    ci: "",
    age: "83",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "202",
    lastName: "VASQUE LUIS",
    ci: "",
    age: "77",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "206",
    lastName: "MENDEZ YESIRE",
    ci: "",
    age: "24",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "207",
    lastName: "PARRA ESTEFANÍA",
    ci: "",
    age: "15",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "209",
    lastName: "OLDAZ LUISANA",
    ci: "",
    age: "58",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "210",
    lastName: "MACHADO ANARELLA",
    ci: "",
    age: "9",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "212",
    lastName: "SIMENEZ AXIEL",
    ci: "",
    age: "4",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "213",
    lastName: "PEDRON JESÚS",
    ci: "",
    age: "68",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "215",
    lastName: "OMASIENTO SEBASTIÁN",
    ci: "",
    age: "16",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "217",
    lastName: "CABARCA VENDEZILÍN",
    ci: "",
    age: "13",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
  {
    num: "218",
    lastName: "SEQUELA SOFIA",
    ci: "",
    age: "19",
    sex: "",
    origin: "",
    hospital: "Hospital Domingo Luciani (El Llanito)",
    updatedAt: "Archivo maestro 25/06/2026",
    service: "Registro hospitalario",
  },
];
